export const API_ENV_VAR = {
	BETTER_AUTH_BASE_URL: "BETTER_AUTH_BASE_URL",
	BETTER_AUTH_SECRET: "BETTER_AUTH_SECRET",
	CLIENT_ORIGIN: "CLIENT_ORIGIN",
	REDIS_URL: "REDIS_URL",
	S3_ACCESS_KEY_ID: "S3_ACCESS_KEY_ID",
	S3_SECRET_ACCESS_KEY: "S3_SECRET_ACCESS_KEY",
	S3_BUCKET: "S3_BUCKET",
	S3_ENDPOINT: "S3_ENDPOINT",
	S3_REGION: "S3_REGION",
	INNGEST_APP_ID: "INNGEST_APP_ID",
	MCP_SERVER_URL: "MCP_SERVER_URL",
} as const;
